#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5
cd "$(dirname "$0")"

banner "Cloudflare Worker — llms-from-the-top.jessitron.com"

# ── Stage 1: wrangler CLI ─────────────────────────────────────────────────
stage "Install the wrangler CLI"
if command -v wrangler >/dev/null 2>&1; then
  say "Found wrangler: $(wrangler --version 2>/dev/null | head -n1)"
else
  say "wrangler (Cloudflare's Worker CLI) isn't on your PATH."
  if confirm "Install it now with 'npm install -g wrangler'?"; then
    npm install -g wrangler
  else
    warn "Skipping install — re-run this wizard once wrangler is available."
    SKIPPED+=("install wrangler (npm install -g wrangler)")
    pause "Continue?"
  fi
fi

# ── Stage 2: Cloudflare login ─────────────────────────────────────────────
stage "Log in to the Cloudflare account that owns jessitron.com"
if npx --yes wrangler whoami >/dev/null 2>&1; then
  say "Already logged in:"
  npx --yes wrangler whoami || true
else
  say "This opens a browser tab — approve access for the account that manages"
  say "the jessitron.com DNS zone (needed since this Worker's route lives there)."
  npx --yes wrangler login
  if ! npx --yes wrangler whoami >/dev/null 2>&1; then
    warn "Still not logged in — pausing so you can sort it out."
    pause "Continue once login succeeded?"
  fi
fi

# ── Stage 3: DNS record (dashboard, manual) ───────────────────────────────
stage "Add the DNS record in the Cloudflare dashboard"
say "wrangler login only grants Workers scopes, not DNS write access, so it"
say "can't create this record for you — it's a one-time manual step."
if dig +short llms-from-the-top.jessitron.com >/dev/null 2>&1 && \
   [[ -n "$(dig +short llms-from-the-top.jessitron.com 2>/dev/null)" ]]; then
  say "Found an existing DNS record for llms-from-the-top.jessitron.com — skipping."
else
  say "In the dashboard for the jessitron.com zone, add a DNS record:"
  step "Type: CNAME, Name: llms-from-the-top, Target: jessitron.com, Proxy: ON (orange cloud)"
  note "The target doesn't matter — the Worker route below intercepts the"
  note "request before it reaches it. What matters is the record existing"
  note "and being proxied through Cloudflare."
  open_url "https://dash.cloudflare.com/?to=/:account/jessitron.com/dns/records"
  pause "Added the record? Press Enter to continue."
fi

# ── Stage 4: Deploy the Worker ────────────────────────────────────────────
stage "Deploy the Worker"
say "Publishing the Worker and attaching the route"
say "  llms-from-the-top.jessitron.com/* → edge-proxy (from wrangler.toml)"
npx --yes wrangler deploy
note "This just attaches the route to the DNS record from the previous stage."
pause "Continue?"

# ── Stage 5: Smoke test ───────────────────────────────────────────────────
stage "Smoke test the custom domain"
say "Sending a tiny completion request through the new domain."
note "A non-200 here (especially curl exit/HTTP code 000) most likely means"
note "the DNS record from stage 3 is missing or not proxied — not that it"
note "just needs more time. Re-check the dashboard rather than just retrying."
http_code=$(curl -s -o /tmp/llms-from-the-top-smoketest.json -w '%{http_code}' \
  https://llms-from-the-top.jessitron.com/v1/completions \
  -H 'content-type: application/json' \
  -d '{"model": "base", "prompt": "Hello", "max_tokens": 5}') || http_code="000"

if [[ "$http_code" == "200" ]]; then
  say "${GREEN}✓ HTTP 200${RESET} — response body:"
  cat /tmp/llms-from-the-top-smoketest.json
  printf '\n'
else
  warn "Got HTTP $http_code, not 200."
  say "Response body (if any):"
  cat /tmp/llms-from-the-top-smoketest.json 2>/dev/null || true
  SKIPPED+=("verify smoke test — got HTTP $http_code, retry after DNS settles")
fi
rm -f /tmp/llms-from-the-top-smoketest.json
# ──────────────────────────────────────────────────────────────────────────

finish
