name = "llms-from-the-top-edge"
main = "src/index.js"
compatibility_date = "2026-09-14"
compatibility_flags = ["nodejs_compat"]

[vars]
BASE_BACKEND_URL = "https://jessitron--llms-from-the-top-base-serve.modal.run"
CHAT_BACKEND_URL = "https://jessitron--llms-from-the-top-base-serve-chat.modal.run"

[[routes]]
pattern = "llms-from-the-top.jessitron.com"
custom_domain = true
